spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  application:
    name: points-service

  jpa:
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka