spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${LOCAL_DB_NAME}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

  cloud:
    openfeign:
      url: localhost:8080/api/internal

payment:
  client:
    key: ${PAYMENT_CLIENT_KEY}
  secret:
    key: ${PAYMENT_SECRET_KEY}

server:
  error:
    include-message: always
  port: 8081