spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  application:
    name: points-service

  jpa:
    open-in-view: false

  cloud:
    openfeign:
      okhttp:
        enabled: true

server:
#  port: 8081
  port: 0   # 랜덤 포트
  http2:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka

management:
  endpoint:
    health:
      show-details: always
  security:
    enabled: false