spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  application:
    name: points-service

  jpa:
    open-in-view: false


logging:
  level:
    ROOT: INFO
    org.hibernate: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm: TRACE
    org.springframework.transaction: TRACE
    com.zaxxer.hikari: TRACE
    com.mysql.cj.jdbc: TRACE

  cloud:
    openfeign:
      okhttp:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka

management:
  endpoint:
    health:
      show-details: always
  security:
    enabled: false
