spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  application:
    name: points-service

  jpa:
    open-in-view: false

server:
#  port: 8081
  port: 0   # 랜덤 포트

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka