spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]

  jpa:
    open-in-view: false

server:
  port: 8081

logging:
  level:
    ROOT: INFO
    org.hibernate: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm: TRACE
    org.springframework.transaction: TRACE
    com.zaxxer.hikari: TRACE
    com.mysql.cj.jdbc: TRACE